services:
  vue:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue
    volumes:
      - vue-dist:/app/dist
    command: sh -c "npm install && npm run build"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - vue-dist:/usr/share/nginx/html:ro
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - vue
      - symfony-api

  symfony-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: symfony-api
    ports:
      - "9000:9000"




volumes:
  vue-dist:
